apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-helloworld
  template:
    metadata:
      labels:
        app: staging-helloworld
    spec:
      containers:
      - name: staging-helloworld
        image: us-docker.pkg.dev/${{ secrets.DOCKER_HUB_USERNAME }}/helloworld:latest
