apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging
  template:
    metadata:
      labels:
        app: staging
    spec:
      containers:
      - name: staging
        image: gcr.io/${{ secrets.PROJECT_ID }}/static-site:${{ github.sha }}
