# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: echo "${{ secrets.HWORLD }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/helloworld:latest

  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: us-docker.pkg.dev/${{ secrets.DOCKER_HUB_USERNAME }}/helloworld:latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

        # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY_DEC }}
          service_account_email: ${{ secrets.GKE_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}

        # Configure docker to use the gcloud command-line tool as a credential helper coo
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Create Cluster
        run: |-
      #         gcloud auth activate-service-account --key-file ${{ secrets.GKE_SA_KEY_DEC }}
      #         gcloud config set project  ${{ secrets.PROJECT_ID }}
                gcloud container clusters create cluster-for-simple-app --num-nodes=3
                gcloud container clusters get-credentials cluster-for-simple-app
      #         kubectl apply -f deployment.yml
      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed --project ${{ secrets.PROJECT_ID }}

