name: Node.js Package

on:
  push:
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha  }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "Build and push Docker image to container registry"
      - run: echo ${{ github.repository }}
      - run: echo $IMAGE_NAME
